#!/bin/bash

TEST_CMD="/usr/bin/cp-test -t -u -r"
BUILD='false'
DIR="$(git rev-parse --show-toplevel)/docker/"

usage() {
  cat << USAGE

USAGE: test [OPTIONS]

OPTIONS:
  -b        rebuilds the candlepin container
  -c CMD    sets the command to be run by the container
              default: $TEST_CMD
  -m        use mysql
  -o        use oracle
  -p        use postgres

USAGE
}

while getopts ":bc:dmop" opt; do
  case $opt in
    b) BUILD=true;;
    c) TEST_CMD="$OPTARG";;
    m) COMPOSE_ARGS="-f $DIR/docker-compose-mysql.yml";;
    o) COMPOSE_ARGS="-f $DIR/docker-compose-oracle.yml";;
    p) COMPOSE_ARGS="-f $DIR/docker-compose-postgres.yml";;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      usage
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      usage
      exit 1
      ;;
  esac
done

docker-compose stop
docker-compose rm -f -a
[ $BUILD = true ] && docker-compose $COMPOSE_ARGS build
docker-compose $COMPOSE_ARGS run --rm candlepin $TEST_CMD
RETVAL=$?
docker-compose stop

exit $RETVAL
